<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book_category extends Model
{

    protected $guarded = [];

    public function getRouteKeyName()
    {
        return "name"; // TODO: Change the autogenerated stub
    }


}
